/** Default admin property wizard payload — mirrors admin-web/mock/data/propertyForm.ts */

export function createDefaultPropertyForm(code) {
  return {
    code,
    listTitle: '',
    district: '',
    listingLine1: '',
    listingLine2: '',
    auditTag: '—',
    submitterName: '陈思远',
    rowMuted: false,
    types: ['标准厂房'],
    companyName: '广州××实业有限公司',
    address: '广州市黄埔区科学城 XX 路 88 号 A 区',
    lat: '23.179455',
    lng: '113.429512',
    mapTitle: '黄埔科学城 · 单层高标准厂房',
    ownerContact: '王业主 · 业主授权代表',
    photoChecklist: ['门口形象照', '路口进出照'],
    mediaUrls:
      'https://example.com/mock-cover.jpg\nhttps://example.com/mock-floor.jpg\nhttps://example.com/mock-intro.mp4',
    mediaImageUrls: 'https://example.com/mock-cover.jpg\nhttps://example.com/mock-floor.jpg',
    mediaVideoUrls: 'https://example.com/mock-intro.mp4',
    landMu: 12.5,
    actualLandMu: 12.3,
    buildingArea: 4200,
    actualUseArea: 4050,
    floors: 1,
    loadPerSqm: 3,
    workshopSize: '88×48×9',
    loadNote: '牛腿区 10T 预留',
    structureTypes: ['钢构'],
    structureOther: '',
    powerKva: 800,
    transformers: 2,
    freightLifts: 2,
    liftLoadT: 3,
    liftDims: '2.4×3.0×2.8',
    platformHeightCm: 110,
    turnRadiusM: 14,
    dormRent: 450,
    dormDistanceKm: 1.2,
    dining: '集中',
    transitStation: '科学城站',
    stationDistanceM: 820,
    selfUseSqm: 0,
    rentEstimateYear: 0,
    coTenantCount: 0,
    annualRent: null,
    tenantCompanies: '',
    contractYearsLeft: null,
    vacantMonths: 2,
    usageRemark: '现状空置 · 可协商免租期。',
    propertyRights: ['国有土地', '出让'],
    propertyRightsOther: '',
    landUse: ['工业'],
    landUseOther: '',
    certificates: ['房产证', '土地证', '消防验收证'],
    mortgageDispute: '无',
    mortgageNote: '',
    landlordPriceWan: null,
    tradeMode: '出租 · 可谈出售',
    taxFeeNote: '',
    allowedIndustries: '智能制造 · 装配 · 仓储',
    specialLimits: '禁止高噪音喷涂（夜间）',
    fireSystems: ['喷淋', '烟感'],
    fireOther: '',
    firePass: '是',
    monitorCoverage: '全厂区',
    fireFailReason: '',
    highwayKm: 3.5,
    portAirportKm: 45,
    roadLimits: '限高 4.2m',
    rushHour: '无',
    subsidy: '无',
    subsidyDetail: '',
    taxBenefit: '',
    envLevel: '已通过 · HP-2024-0192',
    dischargePermit: '有',
    solar: '可接入',
    highlights: '层高 9m · 卸货平台 · 丙二类消防',
    risks: '邻里夜间装卸噪音敏感',
    assessment: '优先推荐给电子装配 / 轻加工',
    externalStatus: '出租',
    rentSaleType: '出租',
    rentListSqm: 38,
    propertyFee: 2.5,
    contactName: '李昭',
    contactPhone: '13800138001',
    viewingNote: '工作日 9–17；提前 2h 报备车牌。',
    internalNote: '业主配合度高 · 配电增容约 45 工作日。',
  }
}
