-- =============================================================================
-- Industrial Realty — bulk DEMO seed (MySQL 8+ utf8mb4)
-- Generated by scripts/generate-seed-demo-sql.mjs
-- Regenerate:  node scripts/_gen-admin-hash.mjs && node scripts/generate-seed-demo-sql.mjs
-- Login: admin / Admin123!  (all listed admin users share this password hash)
-- Run on a DEV database only. Backup first.
-- Uncomment to select DB:
-- USE industrial_realty;
-- =============================================================================

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

DELETE FROM audit_logs;
DELETE FROM app_messages;
DELETE FROM announcements;
DELETE FROM property_activity_logs;
DELETE FROM viewings;
DELETE FROM deals;
DELETE FROM video_faq;
DELETE FROM customers;
DELETE FROM properties;
DELETE FROM phone_whitelist;
DELETE FROM region_bindings;
DELETE FROM region_tree_lines;
DELETE FROM region_defs;
DELETE FROM staff;
DELETE FROM code_master;
DELETE FROM sys_users;
DELETE FROM app_config;
DELETE FROM security_switches;

SET FOREIGN_KEY_CHECKS = 1;


INSERT INTO sys_users (username, password_hash, display_name, role_line, avatar_url, user_kind, region_line) VALUES
('admin', 'scrypt$05375fec4f1105809488776d5c1db4ae$5deec99ccbde3f9fbd9d83a8f514016365427b5c35e57a14f92efaf01c3fcdd08bc0e31f3ddc8a6523038188ede52f4c38371feeeeb7707c31232eb65d964fe2', '系统管理员', '超级管理员 · 全量配置', 'https://cdn.example.com/avatar/admin.png', 'admin', '黄埔区 · 南沙区 · 增城区'),
('demo_pm', 'scrypt$05375fec4f1105809488776d5c1db4ae$5deec99ccbde3f9fbd9d83a8f514016365427b5c35e57a14f92efaf01c3fcdd08bc0e31f3ddc8a6523038188ede52f4c38371feeeeb7707c31232eb65d964fe2', '王项目', '招商总监 · 项目审批', 'https://cdn.example.com/avatar/pm.png', 'admin', '黄埔区 · 科学城'),
('demo_ops', 'scrypt$05375fec4f1105809488776d5c1db4ae$5deec99ccbde3f9fbd9d83a8f514016365427b5c35e57a14f92efaf01c3fcdd08bc0e31f3ddc8a6523038188ede52f4c38371feeeeb7707c31232eb65d964fe2', '李运营', '运营主管 · 内容审核', 'https://cdn.example.com/avatar/ops.png', 'admin', '南沙区 · 万顷沙'),
('demo_fin', 'scrypt$05375fec4f1105809488776d5c1db4ae$5deec99ccbde3f9fbd9d83a8f514016365427b5c35e57a14f92efaf01c3fcdd08bc0e31f3ddc8a6523038188ede52f4c38371feeeeb7707c31232eb65d964fe2', '赵财务', '财务复核 · 成交台账', 'https://cdn.example.com/avatar/fin.png', 'admin', '天河区 · 珠江新城'),
('demo_hr', 'scrypt$05375fec4f1105809488776d5c1db4ae$5deec99ccbde3f9fbd9d83a8f514016365427b5c35e57a14f92efaf01c3fcdd08bc0e31f3ddc8a6523038188ede52f4c38371feeeeb7707c31232eb65d964fe2', '陈人事', '员工与白名单维护', 'https://cdn.example.com/avatar/hr.png', 'admin', '番禺区 · 市桥'),
('demo_read', 'scrypt$05375fec4f1105809488776d5c1db4ae$5deec99ccbde3f9fbd9d83a8f514016365427b5c35e57a14f92efaf01c3fcdd08bc0e31f3ddc8a6523038188ede52f4c38371feeeeb7707c31232eb65d964fe2', '孙只读', '审计与报表只读角色', 'https://cdn.example.com/avatar/read.png', 'admin', '海珠区 · 琶洲');


INSERT INTO staff (id, employee_no, name, phone, phone_masked, role, regions, status, email, department, title, hire_date, account_status, region_ids_json, data_scope_hint, remark) VALUES
('s-staff-01', 'E2024001', '张晨', '13800001001', '138****1001', '业务员', '黄埔区 · 增城', '正常', 'zhangchen@demo.local', '黄埔业务一部', '高级业务员', '2024-03-01', '正常', '["hp_huangpu","zc_zengcheng"]', '黄埔+增城房源；本人私有客户全量', '擅长制造业客户'),
('s-staff-02', 'E2024002', '王莉', '13800001002', '138****1002', '业务员', '南沙 · 番禺', '正常', 'wangli@demo.local', '南沙业务二部', '业务员', '2024-05-12', '正常', '["ns_nansha","py_panyu"]', '南沙仓储客户为主', '跟进节奏快'),
('s-staff-03', 'E2024003', '刘洋', '13800001003', '138****1003', '部门经理', '黄埔 · 天河', '正常', 'liuyang@demo.local', '黄埔业务一部', '部门经理', '2022-11-20', '正常', '["hp_huangpu","th_tianhe"]', '审批本组发布与带看', '兼管审核'),
('s-staff-04', 'E2024004', '陈思', '13800001004', '138****1004', '业务员', '增城', '正常', 'chens@demo.local', '增城组', '业务员', '2025-01-08', '正常', '["zc_zengcheng"]', '增城独门独院专线', ''),
('s-staff-05', 'E2024005', '周琪', '13800001005', '138****1005', '人事专员', '总部', '正常', 'zhouqi@demo.local', '人事行政', '人事专员', '2023-07-01', '正常', '[]', '白名单与员工档案维护', '不做一线带看'),
('s-staff-06', 'E2024006', '吴峰', '13800001006', '138****1006', '业务员', '白云 · 花都', '冻结（风控）', 'wufeng@demo.local', '北部组', '业务员', '2024-08-15', '冻结（风控）', '["by_baiyun","hd_huadu"]', '账号冻结示例数据', '风控观察期'),
('s-staff-07', 'E2024007', '郑洁', '13800001007', '138****1007', '业务员', '黄埔', '正常', 'zhengjie@demo.local', '黄埔业务一部', '业务员', '2025-02-01', '正常', '["hp_huangpu"]', '新人培训中', '导师：张晨'),
('s-staff-08', 'E2024008', '钱博', '13800001008', '138****1008', '超级管理员', '全市', '正常', 'qianbo@demo.local', '总经办', '数据看板支持', '2021-01-01', '正常', '["hp_huangpu","ns_nansha","zc_zengcheng","th_tianhe"]', '全局只读数据支持', '不参与客户私海');


INSERT INTO region_defs (name, sort_order) VALUES
('黄埔区', 10), ('南沙区', 20), ('增城区', 30), ('天河区', 40), ('番禺区', 50), ('白云区', 60), ('花都区', 70), ('海珠区', 80);


INSERT INTO region_tree_lines (sort_order, line_text, indent_px) VALUES
(1, '华南工业带', 0), (2, '广州片区', 16), (3, '黄埔 · 科学城 · 知识城', 32), (4, '南沙 · 自贸区 · 港口', 32),
(5, '增城 · 开发区', 32), (6, '佛山临广', 16), (7, '东莞临广', 16), (8, '深莞惠联动', 0);


INSERT INTO region_bindings (staff_name, node_ids) VALUES
('张晨', 'hp_huangpu,zc_zengcheng'), ('王莉', 'ns_nansha,py_panyu'), ('刘洋', 'hp_huangpu,th_tianhe'),
('陈思', 'zc_zengcheng'), ('周琪', 'hq_all'), ('钱博', 'hp_huangpu,ns_nansha,zc_zengcheng,th_tianhe');


INSERT INTO phone_whitelist (phone, name, remark, updated_by, updated_at) VALUES
('13800001001', '张晨', '核心销售 · 已绑定员工', 'admin', '2026-01-10 10:00:00'),
('13800001002', '王莉', '南沙组', 'admin', '2026-01-11 11:00:00'),
('13800001003', '刘洋', '经理岗', 'demo_hr', '2026-01-12 09:30:00'),
('13800001004', '陈思', '增城专线', 'admin', '2026-01-13 14:20:00'),
('13800001005', '周琪', '人事行政', 'admin', '2026-01-14 16:00:00'),
('13800001006', '吴峰', '冻结观察', 'demo_pm', '2026-01-15 08:00:00'),
('13800001007', '郑洁', '新人', 'admin', '2026-01-16 17:45:00'),
('13900002000', '外部访客甲', '测试手机号 · 未建员工', 'demo_hr', '2026-01-17 12:00:00');


INSERT INTO properties (id, code, title, district, type, status_tag, audit_state, listing_line1, listing_line2, submitter_name, row_muted, meta_line, price_line, audit_hint, company, addr_kv, map_coord_label, admin_full_form_json, submitted_at, risk_tag) VALUES
('p-id-001', 'P-8821', '黄埔科学城高标准厂房 A 栋', '黄埔区', '标准厂房', '待租', 'live', '层高 8m · 配电 2000KVA', '园区食堂 · 24h 保安 · 卸货平台', '张晨', 0, '科学城板块 · 近地铁', '¥28 元/㎡·月（含税）', '资料齐全 · 可签', '台州星兔塑业有限公司', '[{"k":"面积","v":"8200㎡"},{"k":"消防","v":"丙二类"}]', 'N23.123,E113.456', CAST('{"rentPrice":28,"areaM2":8200}' AS JSON), '2026-01-05 10:00:00', '低'),
('p-id-002', 'P-8822', '南沙万顷沙物流园 B 区', '南沙区', '仓库', '待租', 'pending', '双边月台 · 净高 10m', '待审核 · 缺少环评附件', '王莉', 0, '港口 3km · 高速口 1km', '¥22 元/㎡·月', '请补充环评', '华南冷链物流有限公司', '[{"k":"冷库","v":"5000㎡"}]', 'N22.01,E113.62', CAST('{"coldStorage":true}' AS JSON), '2026-01-18 09:00:00', '中'),
('p-id-003', 'P-8823', '增城开发区独门独院', '增城区', '独门独院厂房', '待售', 'pending', '占地 45 亩 · 建筑 2.1 万㎡', '业主急售 · 股权清晰', '陈思', 0, '国家级开发区政策', '¥6800 万可谈', '产权清晰', '增城产业园投资发展有限公司', '[]', NULL, CAST('{"landMu":45,"buildM2":21000}' AS JSON), '2026-01-17 15:30:00', '中高'),
('p-id-004', 'P-8824', '天河智慧城研发办公', '天河区', '写字楼', '意向中', 'live', '精装交付 · 工位 200+', '可分割 · 含税物业', '刘洋', 1, '地铁上盖', '¥95 元/㎡·月', '需年签', '广州某科技公司', '[{"k":"工位","v":"220"}]', 'N23.15,E113.38', CAST('{"workstations":220}' AS JSON), NULL, '低'),
('p-id-005', 'P-8825', '番禺石楼标准仓', '番禺区', '仓库', '已租', 'live', '已租 · 保留案例展示', '客户：华东快运', '王莉', 0, '临近港口支线', '已成交', '租约至 2027', '华东快运集团', '[]', NULL, CAST('{"leasedUntil":"2027-06"}' AS JSON), NULL, '低'),
('p-id-006', 'P-8826', '白云神山简易厂房', '白云区', '标准厂房', '驳回', 'rejected', '结构老旧 · 需加固', '驳回原因：消防不达标', '吴峰', 0, '近高速', '¥15 元/㎡·月', '驳回：消防', '某小型加工厂', '[]', NULL, CAST('{"rejectReason":"fire"}' AS JSON), '2026-01-10 11:00:00', '高'),
('p-id-007', 'P-8827', '花都汽车城旁空地', '花都区', '工业用地', '待售', 'live', '可报建 · 七通一平', '土规已调', '郑洁', 0, '汽车产业链聚集', '¥120 万/亩', '土规齐全', '花都产业投资公司', '[{"k":"用地性质","v":"M1"}]', NULL, CAST('{"landUse":"M1"}' AS JSON), NULL, '中'),
('p-id-008', 'P-8828', '海珠琶洲创意园整层', '海珠区', '产业园商铺', '下架封存', 'live', '已下架 · 仅历史', '业主自用', '钱博', 1, '琶洲西区', '已下架', '不再招商', '某文创集团', '[]', NULL, CAST('{"archived":true}' AS JSON), '2025-12-01 10:00:00', '低');


INSERT INTO property_activity_logs (property_code, line_text, sub_text, sort_order) VALUES
('P-8821', '带看', '张晨 · 客户台州星兔 · 2026-01-12', 1),
('P-8821', '报价调整', '¥28→¥27 含税', 2),
('P-8822', '提交审核', '王莉提交', 1),
('P-8822', '风控标注', '缺环评扫描件', 2),
('P-8823', '业主拜访', '陈思 · 现场测绘', 1),
('P-8824', '意向书', '科技公司 LOI 已收', 1),
('P-8825', '成交归档', '华东快运 · 合同备案', 1),
('P-8826', '驳回会议', '消防整改清单已发', 1),
('P-8827', '土规核验', '规划局回函已存档', 1),
('P-8828', '下架', '业主自用通知', 1);


INSERT INTO customers (slug, company, contact_name, phone, phone_masked, grade, grade_tone, title_line, recent_text, next_line, address_hint, demand_summary, deal_status, last_follow_at, next_reminder, owner_name, has_next_reminder_tag, h2, grade_label, reminder_text, reminder_tone, badges_html, last_follow_display, detail_kv_json, timeline_json, follow_grade_value, next_follow_input, inherit_hint, list_on_mini, admin_id) VALUES
('cust-slug-01', '台州星兔塑业有限公司', '张晨', '13812345601', '138****5601', 'A', 'mint', 'A 类重点 · 扩产中', '上周完成验厂', '明天 10:00 电话回访', '黄埔科学城', '需双层厂房 8000㎡+', '洽谈中', '2026-01-10', '明天 10:00', '张晨', '1', '台州星兔 · 扩产', 'A', '系统提醒 · 回访', 'amber', '<span>重点</span>,<span>私有</span>', '2026-01-10 16:00', CAST('[{"k":"预算","v":"月租≤25万"}]' AS JSON), CAST('["2026-01-08 14:00 · 首次拜访","2026-01-09 10:00 · 验厂"]' AS JSON), 'A', '明天', '客户倾向科学城', 1, 'c1'),
('cust-slug-02', '华南冷链物流有限公司', '王莉', '13987654302', '139****4302', 'B', 'cyan', 'B 类 · 冷库需求', '关注南沙仓', '周五 14:00 现场', '南沙万顷沙', '双边月台', '洽谈中', '2026-01-09', '周五 14:00', '王莉', '1', '冷库 5000㎡', 'B', '跟进', 'mint', '<span>公有</span>', '2026-01-09 11:00', CAST('[]' AS JSON), CAST('["2026-01-07 · 电话沟通"]' AS JSON), 'B', '周五', '需环评说明', 1, 'c2'),
('cust-slug-03', '增城产业园投资发展有限公司', '陈思', '13600003303', '136****3303', 'A', 'mint', '土地并购', '已发 LOI', '周三 09:30 法务', '增城开发区', '股权清晰', '洽谈中', '2026-01-11', '周三 09:30', '陈思', '', '并购尽调', 'A', '法务', 'rose', '<span>重点</span>', '2026-01-11 09:00', CAST('[]' AS JSON), CAST('["2026-01-10 · 现场踏勘"]' AS JSON), 'A', '周三', '尽调清单已发', 1, 'c3'),
('cust-slug-04', '广州某科技公司', '刘洋', '13700004404', '137****4404', 'C', 'slate', '研发办公扩租', '对比三处', '下周二复盘', '天河智慧城', '200+ 工位', '洽谈中', '2026-01-08', '下周二', '刘洋', '', '扩租', 'C', '复盘', 'slate', '<span>公有</span>', '2026-01-08 18:00', CAST('[]' AS JSON), CAST('["2026-01-06 · 方案"]' AS JSON), 'C', '下周', '价格敏感', 1, 'c4'),
('cust-slug-05', '华东快运集团', '王莉', '13500005505', '135****5505', 'B', 'cyan', '已租回访', '满意度调查', '月底回访', '番禺石楼', '仓储运营', '已签约', '2026-01-05', '月底', '王莉', '', '回访', 'B', '服务', 'mint', '<span>公有</span>', '2026-01-05 10:00', CAST('[]' AS JSON), CAST('["2025-12-20 · 签约"]' AS JSON), 'B', '月底', '无', 1, 'c2'),
('cust-slug-06', '某小型加工厂', '吴峰', '13400006606', '134****6606', 'D', 'slate', '驳回跟进', '消防整改', '暂停跟进', '白云神山', '简易加工', '暂停', '2026-01-04', '', '吴峰', '', '消防', 'D', '暂停', 'rose', '<span>风险</span>', '2026-01-04 12:00', CAST('[]' AS JSON), CAST('["2026-01-03 · 驳回通知"]' AS JSON), 'D', '', '整改成本高', 0, 'c5'),
('cust-slug-07', '花都产业投资公司', '郑洁', '13300007707', '133****7707', 'B', 'cyan', '工业用地', '报建咨询', '周四材料补充', '花都汽车城', 'M1 用地', '洽谈中', '2026-01-12', '周四', '郑洁', '1', '报建', 'B', '材料', 'cyan', '<span>重点</span>', '2026-01-12 08:00', CAST('[]' AS JSON), CAST('["2026-01-11 · 规划局电话咨询"]' AS JSON), 'B', '周四', '需红线图', 1, 'c6'),
('cust-slug-08', '某文创集团', '钱博', '13200008808', '132****8808', 'C', 'slate', '琶洲下架客户', '历史保留', '无下次', '海珠琶洲', '整层办公', '已结束', '2025-12-01', '', '钱博', '', '结束', 'C', '归档', 'slate', '<span>公有</span>', '2025-12-01 10:00', CAST('[]' AS JSON), CAST('["2025-11-28 · 下架"]' AS JSON), 'C', '', '业主自用', 1, 'c7');


INSERT INTO video_faq (id, keywords, question, industry, video_path, tags_json, mini_program_search, updated_at, summary, meta_line) VALUES
('vf-001', '冷库,电费', '冷库月台高度与卸货效率如何平衡？', '冷链物流', '/videos/cold-dock-001.mp4', CAST('["冷库","月台","电费"]' AS JSON), 1, '2026-01-02', '3 分钟讲清双边月台与回车场地设计要点。', '冷链 · 月台'),
('vf-002', '环评,南沙', '南沙仓储项目环评通常卡在哪几个环节？', '仓储', '/videos/eia-ns-002.mp4', CAST('["环评","南沙"]' AS JSON), 1, '2026-01-03', '材料清单 + 审批节奏 + 常见补件。', '政策 · 环评'),
('vf-003', '独门独院,增城', '增城独门独院拿地后报建周期要多久？', '产业园', '/videos/zc-land-003.mp4', CAST('["增城","报建"]' AS JSON), 0, '2026-01-04', '从控规到施工许可的关键里程碑。', '土地 · 报建'),
('vf-004', '配电,厂房', '厂房配电扩容需要业主配合哪些资料？', '制造业', '/videos/power-004.mp4', CAST('["配电","厂房"]' AS JSON), 1, '2026-01-05', '容量测算 + 供电局流程 + 费用口径。', '工程 · 配电'),
('vf-005', '租金,合同', '租赁合同里哪些条款容易被客户忽略？', '法务', '/videos/lease-005.mp4', CAST('["合同","租金"]' AS JSON), 1, '2026-01-06', '递增、物业费、复原义务示例。', '法务 · 合同'),
('vf-006', '带看,路线', '大客户首次带看路线如何设计更有说服力？', '招商', '/bytes/tour-006.mp4', CAST('["带看","动线"]' AS JSON), 1, '2026-01-07', '样板点顺序与数据看板准备。', '招商 · 带看'),
('vf-007', '消防,整改', '消防驳回后整改复验通常要准备什么？', '安全', '/videos/fire-007.mp4', CAST('["消防","整改"]' AS JSON), 0, '2026-01-08', '第三方检测与资料归档清单。', '安全 · 消防'),
('vf-008', '成交,台账', '成交台账字段如何与客户财务对齐？', '财务', '/videos/deal-008.mp4', CAST('["成交","台账"]' AS JSON), 1, '2026-01-09', '发票类型、佣金计提节点说明。', '财务 · 台账');


INSERT INTO viewings (slot_start, slot_end, property_ref, customer_name, customer_slug, companions, score, mini_prop_code, mini_staff) VALUES
('2026-01-20 10:00', '2026-01-20 11:30', 'P-8821 黄埔科学城 A 栋', '台州星兔塑业', 'cust-slug-01', '张晨,陈思', 'A', 'P-8821', '张晨'),
('2026-01-21 14:00', '2026-01-21 15:00', 'P-8822 南沙物流园', '华南冷链', 'cust-slug-02', '王莉', 'B', 'P-8822', '王莉'),
('2026-01-22 09:30', '2026-01-22 10:30', 'P-8824 天河智慧城', '广州某科技', 'cust-slug-04', '刘洋,郑洁', 'A', 'P-8824', '刘洋'),
('2026-01-23 16:00', '2026-01-23 17:00', 'P-8823 增城开发区', '增城产业园', 'cust-slug-03', '陈思', 'A', 'P-8823', '陈思'),
('2026-01-24 11:00', '2026-01-24 12:00', 'P-8825 番禺石楼仓', '华东快运', 'cust-slug-05', '王莉,钱博', 'B', 'P-8825', '王莉'),
('2026-01-25 15:30', '2026-01-25 16:30', 'P-8827 花都空地', '花都产业投资', 'cust-slug-07', '郑洁', 'B', 'P-8827', '郑洁'),
('2026-01-26 10:00', '2026-01-26 11:00', 'P-8821 黄埔科学城', '台州星兔塑业', 'cust-slug-01', '张晨', 'A', 'P-8821', '张晨'),
('2026-01-27 13:00', '2026-01-27 14:30', 'P-8826 白云神山', '某小型加工厂', 'cust-slug-06', '吴峰', 'C', 'P-8826', '吴峰');


INSERT INTO deals (contract_type, amount, commission, invoice_type, archive_status, staff_id, staff_name) VALUES
('租赁合同', '¥128万/年', '¥12.8万', '专票', '待归档', 's-staff-01', '张晨'),
('租赁合同', '¥86万/年', '¥8.6万', '普票', '已归档', 's-staff-02', '王莉'),
('买卖合同', '¥6800万', '¥136万', '专票', '待归档', 's-staff-03', '刘洋'),
('服务合同', '¥9.6万/年', '¥0.96万', '电子普票', '待归档', 's-staff-04', '陈思'),
('租赁合同', '¥210万/年', '¥21万', '专票', '已归档', 's-staff-01', '张晨'),
('框架协议', '¥0（框架）', '¥0', '不涉及', '待归档', 's-staff-07', '郑洁'),
('租赁合同', '¥45万/年', '¥4.5万', '专票', '已归档', 's-staff-02', '王莉'),
('居间合同', '¥30万（一次性）', '¥30万', '专票', '待归档', 's-staff-04', '陈思');


INSERT INTO announcements (title, scope, popup, popup_start_at, popup_end_at, status, status_tone, body_text) VALUES
('园区电费计价规则调整', '全员', '是', '2026-06-01 00:00:00', '2026-12-31 23:59:59', '必读', 'amber', '自 6 月起执行分时电价，对内公示，禁止外链。附件：园区配电负荷表、峰谷时段表。联系人：物业中心。'),
('春节放假与值班安排', '全员', '否', NULL, NULL, '通知', 'slate', '2026-01-28 至 02-04 放假；值班电话见内网。紧急报修走 400-xxx。'),
('南沙港区临时交通管制', '南沙组', '是', '2026-01-19 08:00:00', '2026-01-25 20:00:00', '提醒', 'cyan', '大型设备进场高峰，请提前与客户确认路线与到货时段。'),
('黄埔科学城道路施工', '黄埔组', '否', NULL, NULL, '提醒', 'mint', '科丰路部分车道封闭，带看请预留 15 分钟绕行。'),
('客户数据导出审批加强', '全员', '否', NULL, NULL, '制度', 'rose', '批量导出客户与房源需双人复核；审计日志保留 365 天。'),
('新员工系统培训', '总部', '否', NULL, NULL, '培训', 'slate', '本周五 15:00 会议室 A：CRM 与小程序操作演示。'),
('成交台账字段对齐说明', '财务/运营', '否', NULL, NULL, '必读', 'amber', '发票类型、佣金计提节点与合同附件命名规范。'),
('小程序手机号白名单更新流程', '人事', '否', NULL, NULL, '流程', 'cyan', '新增白名单需同步员工档案手机号，避免双重校验失败。');


INSERT INTO app_messages (id, icon, icon_tone, title, hint, time_text, nav, prop_id, customer_id, sort_order) VALUES
('msg-001', 'bell', 'cyan', '待办：3 个客户回访', '张晨 · 台州星兔 / 王莉 · 冷链', '今天 09:10', 'customer-detail', NULL, 'cust-slug-01', 1),
('msg-002', 'doc', 'amber', '房源 P-8822 待补充环评', '审核队列等待材料', '今天 09:20', 'property-detail', 'P-8822', NULL, 2),
('msg-003', 'user', 'mint', '新员工郑洁已完成入职手续', '导师：张晨', '昨天 18:00', NULL, NULL, NULL, 3),
('msg-004', 'warn', 'rose', '风控：客户 cust-slug-06 暂停跟进', '消防整改未完成', '昨天 11:30', 'customer-detail', NULL, 'cust-slug-06', 4),
('msg-005', 'map', 'slate', '带看：明天 10:00 黄埔科学城', '台州星兔 · 张晨', '今天 08:50', NULL, 'P-8821', 'cust-slug-01', 5),
('msg-006', 'money', 'cyan', '成交备案：华东快运待归档', '赵财务请处理', '今天 10:05', NULL, NULL, NULL, 6),
('msg-007', 'shield', 'amber', '安全策略：禁止长按复制已开启', '系统设置生效', '前天', 'settings', NULL, NULL, 7),
('msg-008', 'video', 'mint', '视频 FAQ：冷库月台上新', '小程序可搜关键字「冷库」', '今天 07:55', 'video-faq', NULL, NULL, 8);


INSERT INTO audit_logs (time_text, actor, object_label, action_label, detail, kind, action, sort_order) VALUES
('2026-01-18 09:12', '张晨', '客户 台州星兔', '更新跟进', '电话回访记录已保存', 'cust', 'edit', 0),
('2026-01-18 09:30', '王莉', '房源 P-8822', '提交审核', '补充环评说明待上传', 'prop', 'edit', 0),
('2026-01-17 16:00', '刘洋', '客户 广州某科技', '查看详情', '对比三处方案', 'cust', 'view', 0),
('2026-01-17 14:20', '陈思', '房源 P-8823', '更新挂牌', '价格微调说明', 'prop', 'edit', 0),
('2026-01-16 11:11', 'demo_ops', '公告 电费规则', '发布公告', '全员必读', 'acct', 'edit', 0),
('2026-01-16 10:00', '赵财务', '成交 华东快运', '导出台账', 'CSV 已下载', 'acct', 'view', 0),
('2026-01-15 17:45', '陈人事', '白名单 13900002000', '新增记录', '外部访客甲', 'acct', 'edit', 0),
('2026-01-15 09:00', '钱博', '房源 P-8828', '下架归档', '业主自用', 'prop', 'edit', 0),
('2026-01-14 13:30', '吴峰', '客户 某小型加工厂', '标记暂停', '消防整改', 'cust', 'edit', 0),
('2026-01-13 08:08', 'admin', '用户 demo_pm', '登录成功', 'IP 192.168.1.10', 'acct', 'view', 0),
('2026-01-12 19:00', '郑洁', '客户 花都产业投资', '更新材料', '红线图补充', 'cust', 'edit', 0),
('2026-01-11 12:00', '周琪', '员工 s-staff-07', '更新档案', '导师绑定', 'acct', 'edit', 0);


INSERT INTO code_master (type_code, item_code, label, sort_order, is_active, remark) VALUES
('staff_role', 'sales', '业务员', 10, 1, '系统预置'),
('staff_role', 'dept_mgr', '部门经理', 20, 1, '系统预置'),
('staff_role', 'super_admin', '超级管理员', 30, 1, '系统预置'),
('staff_account_status', 'ok', '正常', 10, 1, '系统预置'),
('staff_account_status', 'disabled_resigned', '禁用（离职）', 20, 1, '系统预置'),
('staff_account_status', 'frozen_risk', '冻结（风控）', 30, 1, '系统预置'),
('staff_department', 'hq', '总经办', 10, 1, '系统预置'),
('staff_department', 'hp1', '黄埔业务一部', 20, 1, '系统预置'),
('staff_department', 'ns2', '南沙业务二部', 30, 1, '系统预置'),
('staff_department', 'ops', '运营中心', 40, 1, '系统预置'),
('staff_department', 'hr', '人事行政', 50, 1, '系统预置'),
('staff_job_title', 'director', '部门总监', 10, 1, '系统预置'),
('staff_job_title', 'mgr', '业务经理', 20, 1, '系统预置'),
('staff_job_title', 'senior_sales', '高级业务员', 30, 1, '系统预置'),
('staff_job_title', 'sales', '业务员', 40, 1, '系统预置'),
('staff_job_title', 'hr_staff', '人事专员', 50, 1, '系统预置'),
('property_type', 'standard', '标准厂房', 10, 1, '系统预置'),
('property_type', 'standalone', '独门独院厂房', 20, 1, '系统预置'),
('property_type', 'warehouse', '仓库', 30, 1, '系统预置'),
('property_type', 'land_ind', '工业用地', 40, 1, '系统预置'),
('property_type', 'office', '写字楼', 50, 1, '系统预置'),
('property_type', 'park_shop', '产业园商铺', 60, 1, '系统预置'),
('property_status_tag', 'draft', '草稿', 10, 1, '系统预置'),
('property_status_tag', 'pending_audit', '待审核', 20, 1, '系统预置'),
('property_status_tag', 'rejected', '驳回', 30, 1, '系统预置'),
('property_status_tag', 'for_rent', '待租', 40, 1, '系统预置'),
('property_status_tag', 'rented', '已租', 50, 1, '系统预置'),
('property_status_tag', 'for_sale', '待售', 60, 1, '系统预置'),
('property_status_tag', 'sold', '已售', 70, 1, '系统预置'),
('property_status_tag', 'intent', '意向中', 80, 1, '系统预置'),
('property_status_tag', 'archived', '下架封存', 90, 1, '系统预置'),
('property_listing_status', 'for_rent', '待租', 10, 1, '系统预置'),
('property_listing_status', 'rented', '已租', 20, 1, '系统预置'),
('property_listing_status', 'for_sale', '待售', 30, 1, '系统预置'),
('property_listing_status', 'sold', '已售', 40, 1, '系统预置'),
('property_listing_status', 'for_rent_sale', '待租售', 45, 1, '系统预置'),
('property_listing_status', 'intent', '意向中', 50, 1, '系统预置'),
('property_listing_status', 'archived', '下架封存', 60, 1, '系统预置'),
('staff_role', 'trainee', '见习业务员', 5, 1, '演示扩展'),
('staff_role', 'channel', '渠道顾问', 15, 1, '演示扩展'),
('staff_department', 'legal', '法务合规', 55, 1, '演示扩展'),
('staff_department', 'finance', '财务中心', 60, 1, '演示扩展'),
('staff_job_title', 'intern', '实习生', 60, 1, '演示扩展'),
('staff_job_title', 'specialist', '运营专员', 55, 1, '演示扩展'),
('property_type', 'cold_chain', '冷链仓', 35, 1, '演示扩展'),
('property_type', 'rd_office', '研发办公', 45, 1, '演示扩展'),
('property_status_tag', 'in_review', '复审中', 25, 1, '演示扩展'),
('property_status_tag', 'withdrawn', '已撤回', 35, 0, '演示扩展-停用'),
('property_listing_status', 'reserved', '预留', 70, 1, '演示扩展'),
('staff_account_status', 'probation', '试用期', 40, 1, '演示扩展');

INSERT INTO code_master (type_code, item_code, label, sort_order, is_active, remark) VALUES
('demo_bulk', 'item_001', '演示字典项 1', 1, 1, '批量演示 type=demo_bulk'),
('demo_bulk', 'item_002', '演示字典项 2', 2, 1, '批量演示 type=demo_bulk'),
('demo_bulk', 'item_003', '演示字典项 3', 3, 1, '批量演示 type=demo_bulk'),
('demo_bulk', 'item_004', '演示字典项 4', 4, 1, '批量演示 type=demo_bulk'),
('demo_bulk', 'item_005', '演示字典项 5', 5, 1, '批量演示 type=demo_bulk'),
('demo_bulk', 'item_006', '演示字典项 6', 6, 1, '批量演示 type=demo_bulk'),
('demo_bulk', 'item_007', '演示字典项 7', 7, 1, '批量演示 type=demo_bulk'),
('demo_bulk', 'item_008', '演示字典项 8', 8, 1, '批量演示 type=demo_bulk'),
('demo_bulk', 'item_009', '演示字典项 9', 9, 1, '批量演示 type=demo_bulk'),
('demo_bulk', 'item_010', '演示字典项 10', 10, 1, '批量演示 type=demo_bulk'),
('demo_bulk', 'item_011', '演示字典项 11', 11, 1, '批量演示 type=demo_bulk'),
('demo_bulk', 'item_012', '演示字典项 12', 12, 1, '批量演示 type=demo_bulk'),
('demo_bulk', 'item_013', '演示字典项 13', 13, 1, '批量演示 type=demo_bulk'),
('demo_bulk', 'item_014', '演示字典项 14', 14, 1, '批量演示 type=demo_bulk'),
('demo_bulk', 'item_015', '演示字典项 15', 15, 1, '批量演示 type=demo_bulk'),
('demo_bulk', 'item_016', '演示字典项 16', 16, 1, '批量演示 type=demo_bulk'),
('demo_bulk', 'item_017', '演示字典项 17', 17, 1, '批量演示 type=demo_bulk'),
('demo_bulk', 'item_018', '演示字典项 18', 18, 1, '批量演示 type=demo_bulk'),
('demo_bulk', 'item_019', '演示字典项 19', 19, 1, '批量演示 type=demo_bulk'),
('demo_bulk', 'item_020', '演示字典项 20', 20, 1, '批量演示 type=demo_bulk'),
('demo_bulk', 'item_021', '演示字典项 21', 21, 1, '批量演示 type=demo_bulk'),
('demo_bulk', 'item_022', '演示字典项 22', 22, 1, '批量演示 type=demo_bulk'),
('demo_bulk', 'item_023', '演示字典项 23', 23, 1, '批量演示 type=demo_bulk'),
('demo_bulk', 'item_024', '演示字典项 24', 24, 1, '批量演示 type=demo_bulk'),
('demo_bulk', 'item_025', '演示字典项 25', 25, 1, '批量演示 type=demo_bulk'),
('demo_bulk', 'item_026', '演示字典项 26', 26, 1, '批量演示 type=demo_bulk'),
('demo_bulk', 'item_027', '演示字典项 27', 27, 1, '批量演示 type=demo_bulk'),
('demo_bulk', 'item_028', '演示字典项 28', 28, 1, '批量演示 type=demo_bulk'),
('demo_bulk', 'item_029', '演示字典项 29', 29, 1, '批量演示 type=demo_bulk'),
('demo_bulk', 'item_030', '演示字典项 30', 30, 1, '批量演示 type=demo_bulk'),
('demo_bulk', 'item_031', '演示字典项 31', 31, 1, '批量演示 type=demo_bulk'),
('demo_bulk', 'item_032', '演示字典项 32', 32, 1, '批量演示 type=demo_bulk'),
('demo_bulk', 'item_033', '演示字典项 33', 33, 1, '批量演示 type=demo_bulk'),
('demo_bulk', 'item_034', '演示字典项 34', 34, 1, '批量演示 type=demo_bulk'),
('demo_bulk', 'item_035', '演示字典项 35', 35, 1, '批量演示 type=demo_bulk'),
('demo_bulk', 'item_036', '演示字典项 36', 36, 1, '批量演示 type=demo_bulk'),
('demo_bulk', 'item_037', '演示字典项 37', 37, 1, '批量演示 type=demo_bulk'),
('demo_bulk', 'item_038', '演示字典项 38', 38, 1, '批量演示 type=demo_bulk'),
('demo_bulk', 'item_039', '演示字典项 39', 39, 1, '批量演示 type=demo_bulk'),
('demo_bulk', 'item_040', '演示字典项 40', 40, 1, '批量演示 type=demo_bulk');

INSERT INTO app_config (k, v_json) VALUES
('dashboard', CAST('{"kpis":[{"label":"房源总数","value":"8"},{"label":"待租 / 待售（空置）","value":"4"},{"label":"客户总量","value":"8"},{"label":"成交备案条数","value":"8"}],"regionBars":[{"label":"黄埔区","count":2,"heightPct":100},{"label":"南沙区","count":1,"heightPct":50},{"label":"增城区","count":1,"heightPct":50},{"label":"天河区","count":1,"heightPct":50},{"label":"番禺区","count":1,"heightPct":50},{"label":"白云区","count":1,"heightPct":50},{"label":"花都区","count":1,"heightPct":50},{"label":"海珠区","count":1,"heightPct":50}],"staffActivity":[{"name":"张晨","followUps":12,"viewings":4,"deals":3},{"name":"王莉","followUps":9,"viewings":3,"deals":2},{"name":"刘洋","followUps":7,"viewings":2,"deals":2},{"name":"陈思","followUps":6,"viewings":2,"deals":1},{"name":"郑洁","followUps":4,"viewings":2,"deals":1},{"name":"吴峰","followUps":2,"viewings":1,"deals":0}]}' AS JSON));

DELETE FROM app_config WHERE k = 'workbench';


INSERT INTO security_switches (k, label, enabled) VALUES
('mask_property_contact', '房源联系人脱敏展示', 1),
('mask_customer_phone', '客户手机号脱敏展示', 1),
('forbid_long_press_copy', '禁止长按复制敏感字段', 1),
('audit_publish', '发布前强制审核', 0);


-- =============================================================================
-- Done. Optional: SELECT COUNT(*) FROM properties; etc.
-- =============================================================================
